// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "data-science/index.mdx": () => import("../content/docs/data-science/index.mdx?collection=docs"), "data-science/linear-models.mdx": () => import("../content/docs/data-science/linear-models.mdx?collection=docs"), "data-science/ml-algorithms.mdx": () => import("../content/docs/data-science/ml-algorithms.mdx?collection=docs"), "data-science/neural-networks.mdx": () => import("../content/docs/data-science/neural-networks.mdx?collection=docs"), "data-science/optimization.mdx": () => import("../content/docs/data-science/optimization.mdx?collection=docs"), "data-science/statistics.mdx": () => import("../content/docs/data-science/statistics.mdx?collection=docs"), "swe-prep/data-structures.mdx": () => import("../content/docs/swe-prep/data-structures.mdx?collection=docs"), "swe-prep/divide-and-conquer.mdx": () => import("../content/docs/swe-prep/divide-and-conquer.mdx?collection=docs"), "swe-prep/dynamic-programming.mdx": () => import("../content/docs/swe-prep/dynamic-programming.mdx?collection=docs"), "swe-prep/fft-algorithms.mdx": () => import("../content/docs/swe-prep/fft-algorithms.mdx?collection=docs"), "swe-prep/graph-algorithms.mdx": () => import("../content/docs/swe-prep/graph-algorithms.mdx?collection=docs"), "swe-prep/index.mdx": () => import("../content/docs/swe-prep/index.mdx?collection=docs"), "swe-prep/networking-basics.mdx": () => import("../content/docs/swe-prep/networking-basics.mdx?collection=docs"), "swe-prep/pattern-matching.mdx": () => import("../content/docs/swe-prep/pattern-matching.mdx?collection=docs"), "swe-prep/programming-techniques.mdx": () => import("../content/docs/swe-prep/programming-techniques.mdx?collection=docs"), "swe-prep/software-design.mdx": () => import("../content/docs/swe-prep/software-design.mdx?collection=docs"), "swe-prep/sorting-algorithms.mdx": () => import("../content/docs/swe-prep/sorting-algorithms.mdx?collection=docs"), "trading-prep/combinatorics.mdx": () => import("../content/docs/trading-prep/combinatorics.mdx?collection=docs"), "trading-prep/conditional-probability.mdx": () => import("../content/docs/trading-prep/conditional-probability.mdx?collection=docs"), "trading-prep/expected-values.mdx": () => import("../content/docs/trading-prep/expected-values.mdx?collection=docs"), "trading-prep/index.mdx": () => import("../content/docs/trading-prep/index.mdx?collection=docs"), "trading-prep/limit-theorems.mdx": () => import("../content/docs/trading-prep/limit-theorems.mdx?collection=docs"), "trading-prep/random-variables.mdx": () => import("../content/docs/trading-prep/random-variables.mdx?collection=docs"), "trading-prep/stochastic-calculus.mdx": () => import("../content/docs/trading-prep/stochastic-calculus.mdx?collection=docs"), }),
};
export default browserCollections;